cc_library(
    name = "http_server",
    hdrs = ["http_server.h"],
    strip_include_prefix = "",
    include_prefix = "server",
    visibility = ["//visibility:public"],
    deps = [
        "//src/core:common",
    ],
)
