cc_test(
    name = "stack_merger_processor_test",
    srcs = ["stack_merger_processor_test.cc"],
    deps = [
        "//src/processors:stack_merger",
        "//src/core:engine",
        "//src/core:common",
        "@googletest//:gtest_main",
    ],
)
