module(
    name = "illuminator",
    version = "0.1.0",
)

bazel_dep(name = "rules_cc", version = "0.0.17")
bazel_dep(name = "platforms", version = "0.0.10")
bazel_dep(name = "bazel_skylib", version = "1.7.1")
bazel_dep(name = "abseil-cpp", version = "20240722.0", repo_name = "com_google_absl")
bazel_dep(name = "nlohmann_json", version = "3.11.3", repo_name = "nlohmann_json")
bazel_dep(name = "yaml-cpp", version = "0.8.0", repo_name = "yaml_cpp")
bazel_dep(name = "googletest", version = "1.15.2", repo_name = "com_google_googletest")
bazel_dep(name = "spdlog", version = "1.14.1")
bazel_dep(name = "fmt", version = "10.2.1")
