cc_test(
    name = "otlp_export_sink_test",
    srcs = ["otlp_export_sink_test.cc"],
    deps = [
        "//src/sinks:otlp_export",
        "//src/core:engine",
        "//src/core:common",
        "@googletest//:gtest_main",
    ],
)
