cc_test(
    name = "websocket_sink_test",
    srcs = ["websocket_sink_test.cc"],
    deps = [
        "//src/sinks:websocket_sink",
        "//src/core:engine",
        "//src/core:common",
        "@googletest//:gtest_main",
    ],
)
