cc_test(
    name = "pprof_export_sink_test",
    srcs = ["pprof_export_sink_test.cc"],
    deps = [
        "//src/sinks:pprof_export",
        "//src/core:engine",
        "//src/core:common",
        "@googletest//:gtest_main",
    ],
)
