cc_test(
    name = "passthrough_processor_test",
    srcs = ["passthrough_processor_test.cc"],
    deps = [
        "//src/processors:passthrough",
        "//src/core:engine",
        "@googletest//:gtest_main",
    ],
)
