cc_test(
    name = "file_export_sink_test",
    srcs = ["file_export_sink_test.cc"],
    deps = [
        "//src/sinks:file_export",
        "//src/core:engine",
        "//src/core:common",
        "@googletest//:gtest_main",
        "@nlohmann_json//:json",
    ],
)
