cc_test(
    name = "status_test",
    srcs = ["status_test.cc"],
    deps = [
        "//src/core:common",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "config_test",
    srcs = ["config_test.cc"],
    deps = [
        "//src/core:common",
        "@googletest//:gtest_main",
    ],
)
