cc_test(
    name = "cpu_stats_aggregator_test",
    srcs = ["cpu_stats_aggregator_test.cc"],
    deps = [
        "//src/aggregators:cpu_stats_aggregator",
        "//src/core:engine",
        "//src/core:common",
        "@googletest//:gtest_main",
    ],
)
