cc_test(
    name = "lock_free_queue_test",
    srcs = ["lock_free_queue_test.cc"],
    deps = [
        "//src/core:memory",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "arena_test",
    srcs = ["arena_test.cc"],
    deps = [
        "//src/core:memory",
        "@googletest//:gtest_main",
    ],
)
