cc_test(
    name = "local_storage_sink_test",
    srcs = ["local_storage_sink_test.cc"],
    deps = [
        "//src/sinks:local_storage",
        "//src/storage:sqlite_backend",
        "//src/core:engine",
        "//src/core:common",
        "@googletest//:gtest_main",
    ],
)
