cc_test(
    name = "sqlite_backend_test",
    srcs = ["sqlite_backend_test.cc"],
    deps = [
        "//src/storage:sqlite_backend",
        "//src/core:common",
        "//src/core:engine",
        "@googletest//:gtest_main",
    ],
)
